# Generated by Django 5.0.6 on 2025-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=111)),
                ('lname', models.CharField(max_length=111)),
                ('phone_Number', models.CharField(max_length=99)),
                ('gender', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('county', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_payer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Desc',
            field=models.CharField(max_length=1000),
        ),
    ]
